version: '3.7'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - backend
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/mydb
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
