# name: Docker Build and Push to ECR

# on:
#   push:
#     branches:
#       - feature/*

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#           aws-region: us-east-1

#       - name: Log in to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build and push Docker image to ECR
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: Dockerfile
#           push: true
#           tags: 692348767810.dkr.ecr.us-east-1.amazonaws.com/fastfood-api/order:latest