name: Run SonarQube Analysis

on:
  push:
    branches:
      - feature/*

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Configuração do Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Executar a análise do SonarQube
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=Tech-Challenge-7SOAT_tech-challenge-7soat \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}